FROM golang:1.10

WORKDIR /go/src/github.com/joemiller/go-jail

RUN apt-get update -q --no-install-recommends \
    && apt-get install -qy \
      libseccomp-dev \
      bats \
    && apt-get -y autoremove \
    && apt-get -y clean \
    && rm -rf /var/lib/apt/lists/* \
    && rm -rf /tmp/*
