---
version: 2
jobs:
  build:
    # need to use VM because the 'make test' requires a --privileged docker container
    machine: true
    steps:
      - checkout
      - run: make build
      - run: make test
      - deploy:
          # NOTE: GITHUB_TOKEN env var must be set
          name: github_release
          command: |
            # Create a tag and release on github using $CIRCLE_BUILD_NUM for successful master builds
            if [[ "${CIRCLE_BRANCH}" == "master" ]]; then
              go get github.com/tcnksm/ghr
              ghr -t $GITHUB_TOKEN -u $CIRCLE_PROJECT_USERNAME -r $CIRCLE_PROJECT_REPONAME --replace \
                "$CIRCLE_BUILD_NUM" \
                ./dist
            fi
